# Generated by Django 4.2.1 on 2023-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouseio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdescription',
            name='img',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
